import {z} from "zod";
import {capabilityPlugin} from "../tools.js";
import {directInboundText} from "../message-pipeline.js";
import {ResponseFeedback,feedbackKind,feedbackStyle} from "../response-feedback.js";
const record=z.object({target_id:z.string(),kind:feedbackKind,owner_quote:z.string().min(1).max(500)});
const style=feedbackStyle.extend({owner_quote:z.string().min(1).max(500)});
const pause=z.object({category:z.enum(["meeting_goals","commitment_reminder"]),paused:z.boolean(),owner_quote:z.string().min(1).max(500)});
const fn=(name:string,description:string,schema:z.ZodType)=>({type:"function" as const,name,description,strict:true,parameters:z.toJSONSchema(schema)});
export function responseFeedbackPlugin(memory:ResponseFeedback,active:{meeting_goals:boolean;commitment_reminder:boolean}){return capabilityPlugin({id:"response-feedback",name:"Response feedback",description:"Explicit, owner-scoped quality feedback and reminder controls.",instructions:[
 "When the owner explicitly says a response was useful, not useful, too long or wrong, record_response_feedback using the relevant recent target ID and their exact words. Resolve the target from the conversation; ask if ambiguous. Never treat silence, elapsed time or a read receipt as feedback. Wrong means investigate the underlying issue, not that recording feedback fixed it. Too long makes ordinary future replies briefer, while preserving required information and explicitly requested detail. A reaction to one item never mutes a person, topic or whole notification stream.",
 "Use set_response_style for an explicitly requested persistent length or tone change. Use set_feedback_reminder_pause only for an explicit pause/resume request about that named reminder category. Ask what 'stop these' refers to if unclear. These controls do not change email alerts, scheduled reminders, event data or commitments. Resuming a category does not enable a globally disabled feature. list_response_feedback shows the actual current settings; do not claim notifications are enabled when its featureEnabled flag is false.",
]},[
 {schema:fn("record_response_feedback","Record explicit feedback about a specific delivered response. Never infer feedback or broaden dismissal into a person/topic block.",record),safeAfterUntrusted:true,run:async(a,c)=>{const v=record.parse(a);return{output:JSON.stringify(await memory.record(c.spaceId,v.target_id,v.kind,v.owner_quote,c.currentSenderText??directInboundText(c.message)??""))};}},
 {schema:fn("set_response_style","Save an explicitly requested ordinary-chat length and tone preference; preserve full drafts and requested detail.",style),safeAfterUntrusted:true,run:async(a,c)=>{const v=style.parse(a);if(!(c.currentSenderText??directInboundText(c.message)??"").includes(v.owner_quote))throw new Error("Quote the owner's explicit style request.");return{output:JSON.stringify(await memory.setStyle(c.spaceId,{length:v.length,tone:v.tone}))};}},
 {schema:fn("set_feedback_reminder_pause","Pause or resume one explicitly named reminder category. Does not switch on globally disabled features.",pause),safeAfterUntrusted:true,run:async(a,c)=>{const v=pause.parse(a);if(!(c.currentSenderText??directInboundText(c.message)??"").includes(v.owner_quote))throw new Error("Quote the owner's explicit pause/resume request.");
 const action=v.paused?/\b(?:pause|stop|disable|turn off)\b/i:/\b(?:resume|unpause|enable|turn on|start again)\b/i;
 if(!action.test(v.owner_quote)||/\b(?:don't|do not|never)\s+(?:pause|stop|disable|resume|unpause|enable|turn off|turn on)\b/i.test(v.owner_quote))throw new Error("Pausing or resuming needs an explicit request; a quality rating is not a mute instruction.");return{output:JSON.stringify({...await memory.pause(c.spaceId,v.category,v.paused),featureEnabled:active[v.category],effective:active[v.category]&&!v.paused})};}},
 {schema:fn("list_response_feedback","Read this chat's recent response targets, recorded feedback, style and reminder preferences.",z.object({})),sideEffecting:false,untrustedSource:true,run:async(_a,c)=>({output:JSON.stringify({...(await memory.get(c.spaceId)??{}),targets:await memory.targets(c.spaceId),featureEnabled:active})})},
]);}
