import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe,it,expect,vi } from "vitest";
import { WorkflowRuns,tickWorkflowRuns } from "./workflow-runs.js";
import { DEFAULT_WORKFLOWS } from "./workflows.js";
const now=new Date("2029-01-01T00:00:00Z"); const due=new Date("2029-01-01T01:00:00Z");
async function setup(){const dir=await mkdtemp(join(tmpdir(),"pingu-runs-"));const file=join(dir,"runs.sqlite");const store=new WorkflowRuns(file);return{store,file,close:async()=>{store.close();await rm(dir,{recursive:true,force:true});}};}
function schedule(store:WorkflowRuns,repeat=0){return store.schedule("owner",DEFAULT_WORKFLOWS[0]!,"Prepare the focus meeting",due.toISOString(),repeat,now);}
describe("durable workflow runs",()=>{
 it("deduplicates scheduling and prevents concurrent claims",async()=>{const {store,file,close}=await setup();const other=new WorkflowRuns(file);try{const run=schedule(store);expect(schedule(store).id).toBe(run.id);expect(store.claim(now)).toBeUndefined();expect(store.claim(due)?.id).toBe(run.id);expect(other.claim(due)).toBeUndefined();}finally{other.close();await close();}});
 it("resumes a checkpoint after lease expiry and rejects stale workers",async()=>{const {store,close}=await setup();try{schedule(store);const old=store.claim(due)!;store.checkpoint(old,'{"input":[],"rounds":1,"reads":1}');const next=store.claim(new Date(due.getTime()+11*60_000))!;expect(next.checkpoint).toContain('"rounds":1');expect(next.token).not.toBe(old.token);expect(()=>store.checkpoint(old,"stale")).toThrow();expect(store.finish(old,"ready","stale")).toBe(false);}finally{await close();}});
 it("persists results before delivery and never resends after uncertain delivery",async()=>{const {store,close}=await setup();try{const run=schedule(store);const execute=vi.fn(async()=>"Source-backed result");const deliver=vi.fn(async()=>{throw new Error("response lost");});const deps={owners:async()=>["owner"],execute,deliver};await tickWorkflowRuns(store,deps,due);expect(store.get(run.id)?.status).toBe("ready");expect(deliver).not.toHaveBeenCalled();await tickWorkflowRuns(store,deps,due);expect(store.get(run.id)).toMatchObject({status:"delivery_unknown",result:"Source-backed result"});await tickWorkflowRuns(store,deps,new Date(due.getTime()+20*60_000));expect(deliver).toHaveBeenCalledOnce();expect(execute).toHaveBeenCalledOnce();}finally{await close();}});
 it("holds a delivery interrupted by a crash",async()=>{const {store,close}=await setup();try{const run=schedule(store);const working=store.claim(due)!;store.finish(working,"ready","saved",due);expect(store.claim(due)?.status).toBe("delivering");store.claim(new Date(due.getTime()+11*60_000));expect(store.get(run.id)?.status).toBe("delivery_unknown");}finally{await close();}});
 it("cancels a whole series and fences an in-flight result",async()=>{const {store,close}=await setup();try{const run=schedule(store,24);const working=store.claim(due)!;expect(store.cancel("guest",run.id)).toBe(false);expect(store.cancel("owner",run.id)).toBe(true);expect(store.finish(working,"ready","late")).toBe(false);expect(store.claim(new Date("2029-01-03"))).toBeUndefined();}finally{await close();}});
 it("coalesces missed repeats instead of flooding catch-up runs",async()=>{const {store,close}=await setup();try{schedule(store,24);expect(store.claim(new Date("2029-01-04T12:00:00Z"))).toBeUndefined();const rows=store.list("owner");expect(rows).toHaveLength(2);expect(rows.find(r=>r.status==="queued")?.dueAt).toBe("2029-01-05T01:00:00.000Z");}finally{await close();}});
 it("bounds retries and cancels revoked owners before execution",async()=>{const {store,close}=await setup();try{const run=schedule(store);const execute=vi.fn(async()=>{throw new Error("offline");});const deps={owners:async()=>["owner"],execute,deliver:vi.fn()};for(let i=0;i<4;i++)await tickWorkflowRuns(store,deps,due);expect(execute).toHaveBeenCalledTimes(3);expect(store.get(run.id)?.status).toBe("failed");const another=store.schedule("revoked",DEFAULT_WORKFLOWS[0]!,"review",due.toISOString(),0,now);await tickWorkflowRuns(store,{...deps,owners:async()=>[]},due);expect(store.get(another.id)?.status).toBe("cancelled");expect(execute).toHaveBeenCalledTimes(3);}finally{await close();}});
 it("forgets private results and all future work for the owner",async()=>{const {store,close}=await setup();try{schedule(store,24);store.forget("owner");expect(store.list("owner")).toEqual([]);}finally{await close();}});
});
